name: whatsapp_clone
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  adaptive_icon_foreground: "assets/image/logo.png"
  adaptive_icon_background: "#ffffff" 

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/Users/
    - assets/image/Status/
    - assets/image/Channels/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/font/helvetica-255/Helvetica-Bold.ttf
        - asset: assets/font/helvetica-255/Helvetica-BoldOblique.ttf
        - asset: assets/font/helvetica-255/helvetica-light-587ebe5a59211.ttf
        - asset: assets/font/helvetica-255/Helvetica-Oblique.ttf
        - asset: assets/font/helvetica-255/Helvetica.ttf
